include $(BUILD_ROOT)/config.mak

W_FLAGS+=-Wno-unknown-pragmas

SOURCES=test.cpp
IDIR+=$(BUILD_ROOT)/KMotionDLL

LD_LIBS+=KMotionX
LD_LIBS+=KMotion 

EXECUTABLE=testRunner
BIN_TYPE=$(EXESUF)

include $(BUILD_ROOT)/include.mk




