include $(BUILD_ROOT)/config.mak
SOURCES=Functions.cpp HiResTimer.cpp CMutex2.cpp SocketWrapper.cpp
IDIR =./include

EXECUTABLE=libKMotionSupport.$(LIBEXT)
SHARED=-shared

include $(BUILD_ROOT)/include.mk