include $(BUILD_ROOT)/config.mak
SOURCES=MessageBox.cpp Functions.cpp HiResTimer.cpp CMutex.cpp SocketWrapper.cpp
IDIR =../include

EXECUTABLE=libKMotionX$(LIBEXT)
SHARED=-shared

include $(BUILD_ROOT)/include.mk