include $(BUILD_ROOT)/config.mak

W_FLAGS+=-Wno-unknown-pragmas

SOURCES=cli.cpp
IDIR+=$(BUILD_ROOT)/KMotionDLL

LD_LIBS+=KMotionX
LD_LIBS+=KMotion 

EXECUTABLE=kflopConsole
BIN_TYPE=$(EXESUF)

include $(BUILD_ROOT)/include.mk




