include $(BUILD_ROOT)/config.mak
SOURCES=cli.cpp
IDIR+=$(BUILD_ROOT)/KMotionX/include
IDIR+=$(BUILD_ROOT)/KMotionX/KMotionSupport/include
IDIR+=$(BUILD_ROOT)/KMotionDLL

LD_LIBS+=KMotionSupport
LD_LIBS+=KMotion 

EXECUTABLE=kflopConsole
SHARED=

include $(BUILD_ROOT)/include.mk




