include $(BUILD_ROOT)/config.mak
SOURCES=KMotionServerX.cpp
IDIR+=$(BUILD_ROOT)/KMotionDLL

LD_LIBS+=KMotionX
LD_LIBS+=KMotion 

EXECUTABLE=KMotionServer
SHARED=

include $(BUILD_ROOT)/include.mk




