include $(BUILD_ROOT)/config.mak
SOURCES=KMotionServerMain.cpp
IDIR+=$(BUILD_ROOT)/Linux/include
IDIR+=$(BUILD_ROOT)/Linux/KMotionSupport/include
IDIR+=$(BUILD_ROOT)/KMotionDLL

LD_LIBS+=KMotionSupport
LD_LIBS+=KMotion 

EXECUTABLE=KMotionServer
SHARED=

include $(BUILD_ROOT)/include.mk




